```%pip install pandas```

In [4]:
import pandas as pd

Let's say you have some data... read it into a Pandas DataFrame

The purpose could vary, but the following operations could be reused for...

In [5]:
# creating a dictionary and turning it into a dataframe...
dictionary1 = {'key': 5}
dataF1 = pd.DataFrame(dictionary1, index=range(len(dictionary1)))
print('convert the defined dictionary to a pandas dataframe')

# cache the info for later by saving it in the same folder as a CSV...
dataF1.to_csv('test.csv', index=False)
dataF1

convert the defined dictionary to a pandas dataframe

   key
0    5

In [6]:
# THEN, reading in as a DataFrame.
dataF1 = pd.read_csv('test.csv')

# Take new, like formatted data...
dictionary2 = {'key': 10}
dataF2 = pd.DataFrame(dictionary2, index=range(len(dictionary2)))
dataF2

   key
0   10

In [7]:
# and combine your data
updated_df = pd.concat([dataF1, dataF2], ignore_index=True)

# cache me outside, how about that?!
updated_df.to_csv('test.csv', index=False)
updated_df

   key
0    5
1   10